
# constraints
# ad9361

#SRIO
set_property PACKAGE_PIN W2 [get_ports srio_txp0]
set_property PACKAGE_PIN U2 [get_ports srio_txp1]
set_property PACKAGE_PIN AB4 [get_ports srio_txp2]
set_property PACKAGE_PIN AA2 [get_ports srio_txp3]
set_property PACKAGE_PIN U5 [get_ports srio_sys_clkn]
create_clock -period 8.000 -name srio_ref_clk -waveform {0.000 4.000} [get_ports srio_sys_clkp]

# AD9361_0
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_0_p]
set_property DIFF_TERM TRUE [get_ports rx_clk_in_0_p]
set_property PACKAGE_PIN Y11 [get_ports rx_clk_in_0_n]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_0_n]
set_property DIFF_TERM TRUE [get_ports rx_clk_in_0_n]

set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_0_p]
set_property DIFF_TERM TRUE [get_ports rx_frame_in_0_p]
set_property PACKAGE_PIN AB17 [get_ports rx_frame_in_0_n]
set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_0_n]
set_property DIFF_TERM TRUE [get_ports rx_frame_in_0_n]

set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[0]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[0]}]
set_property PACKAGE_PIN T9 [get_ports {rx_data_in_0_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[0]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[1]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[1]}]
set_property PACKAGE_PIN AA9 [get_ports {rx_data_in_0_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[1]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[2]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[2]}]
set_property PACKAGE_PIN U8 [get_ports {rx_data_in_0_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[2]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[3]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[3]}]
set_property PACKAGE_PIN Y8 [get_ports {rx_data_in_0_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[3]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[4]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[4]}]
set_property PACKAGE_PIN W8 [get_ports {rx_data_in_0_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[4]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_p[5]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_p[5]}]
set_property PACKAGE_PIN V10 [get_ports {rx_data_in_0_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_0_n[5]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_0_n[5]}]

set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_0_p]
set_property PACKAGE_PIN W13 [get_ports tx_clk_out_0_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_0_n]

set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_0_p]
set_property PACKAGE_PIN AB15 [get_ports tx_frame_out_0_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_0_n]

set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[0]}]
set_property PACKAGE_PIN AB8 [get_ports {tx_data_out_0_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[1]}]
set_property PACKAGE_PIN AB12 [get_ports {tx_data_out_0_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[2]}]
set_property PACKAGE_PIN AB10 [get_ports {tx_data_out_0_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[3]}]
set_property PACKAGE_PIN AA11 [get_ports {tx_data_out_0_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[4]}]
set_property PACKAGE_PIN AA16 [get_ports {tx_data_out_0_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_p[5]}]
set_property PACKAGE_PIN AB14 [get_ports {tx_data_out_0_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_0_n[5]}]

# AD9361_1
set_property IOSTANDARD LVDS [get_ports rx_clk_in_1_p]
set_property DIFF_TERM TRUE [get_ports rx_clk_in_1_p]
set_property PACKAGE_PIN G5 [get_ports rx_clk_in_1_n]
set_property IOSTANDARD LVDS [get_ports rx_clk_in_1_n]
set_property DIFF_TERM TRUE [get_ports rx_clk_in_1_n]

set_property IOSTANDARD LVDS [get_ports rx_frame_in_1_p]
set_property DIFF_TERM TRUE [get_ports rx_frame_in_1_p]
set_property PACKAGE_PIN M4 [get_ports rx_frame_in_1_n]
set_property IOSTANDARD LVDS [get_ports rx_frame_in_1_n]
set_property DIFF_TERM TRUE [get_ports rx_frame_in_1_n]

set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[0]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[0]}]
set_property PACKAGE_PIN E1 [get_ports {rx_data_in_1_n[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[0]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[1]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[1]}]
set_property PACKAGE_PIN J1 [get_ports {rx_data_in_1_n[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[1]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[2]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[2]}]
set_property PACKAGE_PIN L5 [get_ports {rx_data_in_1_n[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[2]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[3]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[3]}]
set_property PACKAGE_PIN H3 [get_ports {rx_data_in_1_n[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[3]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[4]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[4]}]
set_property PACKAGE_PIN H1 [get_ports {rx_data_in_1_n[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[4]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_p[5]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_p[5]}]
set_property PACKAGE_PIN G3 [get_ports {rx_data_in_1_n[5]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_1_n[5]}]
set_property DIFF_TERM TRUE [get_ports {rx_data_in_1_n[5]}]

set_property IOSTANDARD LVDS [get_ports tx_clk_out_1_p]
set_property PACKAGE_PIN K4 [get_ports tx_clk_out_1_n]
set_property IOSTANDARD LVDS [get_ports tx_clk_out_1_n]

set_property IOSTANDARD LVDS [get_ports tx_frame_out_1_p]
set_property PACKAGE_PIN L6 [get_ports tx_frame_out_1_n]
set_property IOSTANDARD LVDS [get_ports tx_frame_out_1_n]

set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[0]}]
set_property PACKAGE_PIN H6 [get_ports {tx_data_out_1_n[0]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[0]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[1]}]
set_property PACKAGE_PIN F4 [get_ports {tx_data_out_1_n[1]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[1]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[2]}]
set_property PACKAGE_PIN G7 [get_ports {tx_data_out_1_n[2]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[2]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[3]}]
set_property PACKAGE_PIN F6 [get_ports {tx_data_out_1_n[3]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[3]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[4]}]
set_property PACKAGE_PIN N6 [get_ports {tx_data_out_1_n[4]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[4]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_p[5]}]
set_property PACKAGE_PIN K6 [get_ports {tx_data_out_1_n[5]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_1_n[5]}]


## SPI0 (MOVE OUT TO GPIO PORTS)
#set_property  -dict {PACKAGE_PIN  N17  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_miso] ; ## SPI0_ZYNQ_MISO
#set_property  -dict {PACKAGE_PIN  P18  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_mosi] ; ## SPI0_ZYNQ_MOSI
#set_property  -dict {PACKAGE_PIN  N18  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_clk] ;  ## SPI0_ZYNQ_SCK
#set_property  -dict {PACKAGE_PIN  T16  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_csn0] ; ## SPI0_ASFE_SPI_CS
#set_property  -dict {PACKAGE_PIN  P19  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_csn1] ; ## SPI0_TRSS_CS
#set_property  -dict {PACKAGE_PIN  U19  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_csn2] ; ## SPI0_ATMEL_SS
#set_property  -dict {PACKAGE_PIN  Y17  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_csn3] ; ## SPI0_LV595_SS
#set_property  -dict {PACKAGE_PIN  Y18  IOSTANDARD LVCMOS33  PULLTYPE PULLUP} [get_ports spi0_csn4] ; ## SPI0_LMK04906_SS

## SPI1
#set_property  -dict {PACKAGE_PIN  A2  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi1_miso]        ; ## PL_Bank35_SPI1_MISO
#set_property  -dict {PACKAGE_PIN  B2  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi1_mosi]        ; ## PL_Bank35_SPI1_MOSI
#set_property  -dict {PACKAGE_PIN  A1  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi1_clk]         ; ## PL_Bank35_SPI1_CK
#set_property  -dict {PACKAGE_PIN  B4  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi1_csn0]        ; ## PL_Bank35_SPI1_AD1_CS
#set_property  -dict {PACKAGE_PIN  A4  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi1_csn1]        ; ## PL_Bank35_SPI1_AD2_CS
#C2 SPI1_ADF5355_1_SS
#D1 SPI1_ADF5355_2_SS


##  GPIO
##  LEDs
set_property PACKAGE_PIN Y22 [get_ports {ps7_gpio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[0]}]
set_property PACKAGE_PIN V21 [get_ports {ps7_gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[1]}]
set_property PACKAGE_PIN V22 [get_ports {ps7_gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[2]}]
set_property PACKAGE_PIN W19 [get_ports {ps7_gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[3]}]

## ADI reset
set_property PACKAGE_PIN T11 [get_ports {ps7_gpio[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[4]}]
set_property PACKAGE_PIN C3 [get_ports {ps7_gpio[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[5]}]

## ASFE signals
set_property PACKAGE_PIN AA22 [get_ports {ps7_gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[6]}]
set_property PACKAGE_PIN AB22 [get_ports {ps7_gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[7]}]
set_property PACKAGE_PIN W21 [get_ports {ps7_gpio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[8]}]
set_property PACKAGE_PIN AA20 [get_ports {ps7_gpio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[9]}]
set_property PACKAGE_PIN U18 [get_ports {ps7_gpio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[10]}]
set_property PACKAGE_PIN V18 [get_ports {ps7_gpio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[11]}]
set_property PACKAGE_PIN N20 [get_ports {ps7_gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[12]}]
set_property PACKAGE_PIN P20 [get_ports {ps7_gpio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[13]}]
set_property PACKAGE_PIN AB20 [get_ports {ps7_gpio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[14]}]
set_property PACKAGE_PIN Y21 [get_ports {ps7_gpio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[15]}]
set_property PACKAGE_PIN AA21 [get_ports {ps7_gpio[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[16]}]

## SPI1
set_property PACKAGE_PIN A2 [get_ports {ps7_gpio[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[17]}]
set_property PULLUP true [get_ports {ps7_gpio[17]}]
set_property PACKAGE_PIN B2 [get_ports {ps7_gpio[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[18]}]
set_property PULLUP true [get_ports {ps7_gpio[18]}]
set_property PACKAGE_PIN A1 [get_ports {ps7_gpio[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[19]}]
set_property PULLUP true [get_ports {ps7_gpio[19]}]

set_property PACKAGE_PIN U19 [get_ports {ps7_gpio[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[20]}]
set_property PULLUP true [get_ports {ps7_gpio[20]}]
set_property PACKAGE_PIN Y17 [get_ports {ps7_gpio[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[21]}]
set_property PULLUP true [get_ports {ps7_gpio[21]}]
set_property PACKAGE_PIN Y18 [get_ports {ps7_gpio[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[22]}]
set_property PULLUP true [get_ports {ps7_gpio[22]}]
set_property PACKAGE_PIN B4 [get_ports {ps7_gpio[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[23]}]
set_property PULLUP true [get_ports {ps7_gpio[23]}]
set_property PACKAGE_PIN A4 [get_ports {ps7_gpio[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[24]}]
set_property PULLUP true [get_ports {ps7_gpio[24]}]
set_property PACKAGE_PIN C2 [get_ports {ps7_gpio[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[25]}]
set_property PULLUP true [get_ports {ps7_gpio[25]}]
set_property PACKAGE_PIN D1 [get_ports {ps7_gpio[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[26]}]
set_property PULLUP true [get_ports {ps7_gpio[26]}]

set_property PACKAGE_PIN P21 [get_ports {ps7_gpio[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[27]}]
set_property PACKAGE_PIN R21 [get_ports {ps7_gpio[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[28]}]

set_property PACKAGE_PIN AB19 [get_ports {ps7_gpio[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[29]}]
set_property PACKAGE_PIN N21 [get_ports {ps7_gpio[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[30]}]
set_property PULLUP true [get_ports {ps7_gpio[30]}]
set_property PACKAGE_PIN N22 [get_ports {ps7_gpio[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[31]}]
set_property PULLUP true [get_ports {ps7_gpio[31]}]
set_property PACKAGE_PIN C1 [get_ports {ps7_gpio[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[32]}]
set_property PACKAGE_PIN T15 [get_ports {ps7_gpio[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[33]}]
set_property PACKAGE_PIN E3 [get_ports {ps7_gpio[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[34]}]

## SPI0
set_property PACKAGE_PIN N17 [get_ports {ps7_gpio[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[35]}]
set_property PULLUP true [get_ports {ps7_gpio[35]}]
set_property PACKAGE_PIN P18 [get_ports {ps7_gpio[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[36]}]
set_property PULLUP true [get_ports {ps7_gpio[36]}]
set_property PACKAGE_PIN N18 [get_ports {ps7_gpio[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[37]}]
set_property PULLUP true [get_ports {ps7_gpio[37]}]
set_property PACKAGE_PIN T16 [get_ports {ps7_gpio[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[38]}]
set_property PULLUP true [get_ports {ps7_gpio[38]}]
set_property PACKAGE_PIN P19 [get_ports {ps7_gpio[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps7_gpio[39]}]
set_property PULLUP true [get_ports {ps7_gpio[39]}]

set_property PACKAGE_PIN W15 [get_ports {ps7_gpio[40]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[40]}]
set_property PACKAGE_PIN T12 [get_ports {ps7_gpio[41]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[41]}]
set_property PACKAGE_PIN U12 [get_ports {ps7_gpio[42]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[42]}]
set_property PACKAGE_PIN V16 [get_ports {ps7_gpio[43]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[43]}]
set_property PACKAGE_PIN W16 [get_ports {ps7_gpio[44]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[44]}]
set_property PACKAGE_PIN U13 [get_ports {ps7_gpio[45]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[45]}]
set_property PACKAGE_PIN V11 [get_ports {ps7_gpio[46]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ps7_gpio[46]}]

set_property PACKAGE_PIN P3 [get_ports {ps7_gpio[47]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[47]}]
set_property PACKAGE_PIN M3 [get_ports {ps7_gpio[48]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[48]}]
set_property PACKAGE_PIN M2 [get_ports {ps7_gpio[49]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[49]}]
set_property PACKAGE_PIN K3 [get_ports {ps7_gpio[50]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[50]}]
set_property PACKAGE_PIN K2 [get_ports {ps7_gpio[51]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[51]}]
set_property PACKAGE_PIN N3 [get_ports {ps7_gpio[52]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[52]}]
set_property PACKAGE_PIN D3 [get_ports {ps7_gpio[53]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ps7_gpio[53]}]



## AXI GPIO

set_property PACKAGE_PIN W11 [get_ports {axi_gpio[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[0]}]
set_property PACKAGE_PIN W10 [get_ports {axi_gpio[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[1]}]
set_property PACKAGE_PIN Y14 [get_ports {axi_gpio[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[2]}]
set_property PACKAGE_PIN Y13 [get_ports {axi_gpio[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[3]}]
set_property PACKAGE_PIN U14 [get_ports {axi_gpio[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[4]}]
set_property PACKAGE_PIN U15 [get_ports {axi_gpio[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[5]}]
set_property PACKAGE_PIN V13 [get_ports {axi_gpio[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[6]}]
set_property PACKAGE_PIN V12 [get_ports {axi_gpio[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {axi_gpio[7]}]

set_property PACKAGE_PIN T20 [get_ports {axi_gpio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[8]}]
set_property PACKAGE_PIN U20 [get_ports {axi_gpio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[9]}]
set_property PACKAGE_PIN R19 [get_ports {axi_gpio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[10]}]
set_property PACKAGE_PIN T19 [get_ports {axi_gpio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[11]}]
set_property PACKAGE_PIN T17 [get_ports {axi_gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[12]}]
set_property PACKAGE_PIN U17 [get_ports {axi_gpio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[13]}]
set_property PACKAGE_PIN R17 [get_ports {axi_gpio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[14]}]
set_property PACKAGE_PIN R18 [get_ports {axi_gpio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio[15]}]



# clocks
create_clock -period 5.000 -name rx_clk_0 [get_ports rx_clk_in_0_p]
create_clock -period 5.000 -name rx_clk_1 [get_ports rx_clk_in_1_p]
create_clock -period 5.000 -name ad9361_0_clk [get_pins i_system_wrapper/system_i/axi_ad9361_0/clk]
create_clock -period 5.000 -name ad9361_1_clk [get_pins i_system_wrapper/system_i/axi_ad9361_1/clk]
create_clock -period 4.000 -name fmc_dma_clk [get_pins i_system_wrapper/system_i/sys_ps7/FCLK_CLK2]

set_clock_groups -asynchronous -group ad9361_0_clk
set_clock_groups -asynchronous -group ad9361_1_clk
set_clock_groups -asynchronous -group fmc_dma_clk


